import { addIcons } from 'ionicons';
import {
  add,
  arrowBackOutline,
  bookOutline,
  cameraOutline,
  cameraReverseOutline,
  chatbubbleEllipsesOutline,
  checkbox,
  checkboxOutline,
  checkmarkCircle,
  checkmarkCircleOutline,
  checkmarkOutline,
  chevronDownOutline,
  close,
  closeCircle,
  closeOutline,
  copyOutline,
  ellipseOutline,
  colorPalette,
  contrastOutline,
  createOutline,
  cut,
  downloadOutline,
  ellipsisVertical,
  eyeOutline,
  eyedrop,
  filter,
  folderOutline,
  helpCircleOutline,
  gridOutline,
  imageOutline,
  images,
  imagesOutline,
  languageOutline,
  linkOutline,
  logoGoogle,
  logOutOutline,
  menu,
  menuOutline,
  moon,
  phonePortraitOutline,
  refresh,
  refreshOutline,
  reloadOutline,
  remove,
  saveOutline,
  scanOutline,
  searchOutline,
  settingsOutline,
  shareOutline,
  shirtOutline,
  swapHorizontalOutline,
  trashOutline,
} from 'ionicons/icons';

/** Register icons used across the app (Ionic 8 standalone). */
export function registerAppIcons(): void {
  addIcons({
    add,
    'arrow-back-outline': arrowBackOutline,
    'book-outline': bookOutline,
    'camera-outline': cameraOutline,
    'camera-reverse-outline': cameraReverseOutline,
    'chatbubble-ellipses-outline': chatbubbleEllipsesOutline,
    checkbox,
    'checkbox-outline': checkboxOutline,
    'checkmark-circle': checkmarkCircle,
    'checkmark-circle-outline': checkmarkCircleOutline,
    'checkmark-outline': checkmarkOutline,
    'chevron-down-outline': chevronDownOutline,
    close,
    'close-circle': closeCircle,
    'close-outline': closeOutline,
    'copy-outline': copyOutline,
    'ellipse-outline': ellipseOutline,
    'color-palette': colorPalette,
    'contrast-outline': contrastOutline,
    'create-outline': createOutline,
    cut,
    'download-outline': downloadOutline,
    'ellipsis-vertical': ellipsisVertical,
    'eye-outline': eyeOutline,
    eyedrop,
    filter,
    'folder-outline': folderOutline,
    'help-circle-outline': helpCircleOutline,
    'grid-outline': gridOutline,
    'image-outline': imageOutline,
    images,
    'images-outline': imagesOutline,
    'language-outline': languageOutline,
    'link-outline': linkOutline,
    'logo-google': logoGoogle,
    'log-out-outline': logOutOutline,
    menu,
    'menu-outline': menuOutline,
    moon,
    'phone-portrait-outline': phonePortraitOutline,
    refresh,
    'refresh-outline': refreshOutline,
    'reload-outline': reloadOutline,
    remove,
    'save-outline': saveOutline,
    'scan-outline': scanOutline,
    'search-outline': searchOutline,
    'settings-outline': settingsOutline,
    'share-outline': shareOutline,
    'shirt-outline': shirtOutline,
    'swap-horizontal-outline': swapHorizontalOutline,
    'trash-outline': trashOutline,
  });
}
